# -*- coding: utf-8 -*-
"""Sentiment_Analysis_TR_Reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jP2DCN9j67s7A8oxIHDh6qppXa7DwCtc

Load data and import libaries
"""

# !pip install datasets

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
from keras import layers, models
from keras.preprocessing.sequence import pad_sequences

from datasets import load_dataset

ds = load_dataset("winvoker/turkish-sentiment-analysis-dataset")
ds

train_data = pd.DataFrame(ds['train'])
test_data = pd.DataFrame(ds['test'])

X_train ,y_train= train_data['text'], train_data['label']
X_test ,y_test= test_data['text'], test_data['label']

nltk.download('stopwords')
stop_words = set(stopwords.words('turkish'))

def remove_stopwords(text):
    kelimeler = text.split()
    temiz_kelimeler = [kelime for kelime in kelimeler if kelime.lower() not in stop_words]
    return ' '.join(temiz_kelimeler)

X_train_clean = X_train.apply(remove_stopwords)
X_test_clean = X_test.apply(remove_stopwords)


tokenizer = Tokenizer(oov_token='<OOV>')
tokenizer.fit_on_texts(X_train_clean)


X_train_seq = tokenizer.texts_to_sequences(X_train_clean)
X_test_seq = tokenizer.texts_to_sequences(X_test_clean)


sequence_lengths = [len(seq) for seq in X_train_seq]
max_length = int(np.percentile(sequence_lengths, 98))


X_train_padded = pad_sequences(X_train_seq, maxlen=max_length, padding='post', truncating='post')
X_test_padded = pad_sequences(X_test_seq, maxlen=max_length, padding='post', truncating='post')

X_train_padded.shape

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

word_index = tokenizer.word_index
reverse_word_index = {value: key for key, value in word_index.items()}
reverse_word_index[0] = '<PAD>'


def sequence_to_text(sequence):
    return ' '.join([reverse_word_index.get(i, '<UNK>') for i in sequence])



print(X_test_padded[12])
print(sequence_to_text(X_test_padded[12]))

# transformers

class TransformerBlock(layers.Layer):

  def __init__(self, embed_size, heads, dropout=0.3):
    super(TransformerBlock, self).__init__()

    self.attention = layers.MultiHeadAttention(num_heads=heads,key_dim=embed_size)
    self.norm1 = layers.LayerNormalization(epsilon=1e-6)  # Normalizasyon katmanı
    self.norm2 = layers.LayerNormalization(epsilon=1e-6)

    self.feed_forward = models.Sequential(
        [
            layers.Dense(embed_size*4,activation = 'relu'),
            layers.Dense(embed_size)
        ]
    )

    self.dropout1 = layers.Dropout(dropout)
    self.dropout2 = layers.Dropout(dropout)

  def call(self, x , training):
     # attention aplly

     attention = self.attention(x,x)
     x = self.norm1(x + self.dropout1(attention,training = training))
     feed_forward = self.feed_forward(x)
     return self.norm2(x+ self.dropout2(feed_forward,training = training))

class TransformerModel(models.Model):
  def __init__(self, num_layers, embed_size, heads, input_dim, output_dim, dropout_rate = 0.1):
    super(TransformerModel,self).__init__()

    self.embedding = layers.Embedding(input_dim = input_dim,output_dim=embed_size)
    self.transformer_blocks = [TransformerBlock(embed_size,heads,dropout_rate) for _ in range(num_layers)]
    self.global_avg_pooling = layers.GlobalAveragePooling1D()
    self.dropout = layers.Dropout(dropout_rate)
    self.fc = layers.Dense(output_dim,activation='softmax')

  def call(self,x,training):
    x = self.embedding(x)
    for transformer in self.transformer_blocks:
      x = transformer(x,  training=training)
    x = self.global_avg_pooling(x)
    x = self.dropout(x,training = training)

    return self.fc(x)

"""model Training

"""

max_features = min(20000, len(word_index) + 1)

num_layers = 4
embed_size = 128
num_heads = 4
input_dim = max_features
output_dim = 3
dropout_rate= 0.1

model = TransformerModel(num_layers, embed_size, num_heads,input_dim, output_dim,dropout_rate)


model.build(input_shape = (None,max_length))

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics=['accuracy'])

model.summary()

"""model fit"""

history = model.fit(X_train_padded,y_train,epochs=5,batch_size=256,validation_data=(X_test_padded,y_test))

plt.figure(figsize=(12, 6))

# Doğruluk grafiği
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Kayıp grafiği
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

def predict_sentiment(text, tokenizer, model, max_len):
    sequence = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(sequence, maxlen=max_len, padding='post')

    prediction = model.predict(padded)[0]  # Tek bir örnek olduğundan [0] ile düzleştiriyoruz
    class_index = np.argmax(prediction)    # En yüksek olasılıklı sınıfın indexini al


    class_labels = {0: "negatif", 1: "nötr", 2: "pozitif"}
    predicted_label = class_labels[class_index]

    confidence = prediction[class_index]
    print(f"Yanlış Oranı: {prediction[0]:.4f} - Nötr Oranı: {prediction[1]:.4f} - Doğru Oranı: {prediction[2]:.4f}")
    return f"Tahmin: {predicted_label} ({confidence:.2f} güven)"

text = """
Yeni gelen güncelleme sayesinde arayüz çok daha modern görünüyor ama kullanım kolaylığı tamamen gitmiş. Bir şeyleri bulmak daha zor artık. Görsellik uğruna işlevsellikten vazgeçilmiş gibi.
"""
result = predict_sentiment(model = model, tokenizer = tokenizer, text = text, max_len = X_train_padded.shape[1])

print(result)

model.save("transformers_sentiment_model_400kdata.h5")